name: FFEX IOS — Build Framework

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Versi build (contoh: v1.0.0)'
        required: false
        default: 'latest'

jobs:
  build:
    name: Compile FFEX.dylib (arm64)
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Select Xcode 15
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

    - name: Compile FFEX.dylib
      run: |
        mkdir -p build

        SDK=$(xcrun --sdk iphoneos --show-sdk-path)

        clang \
          -arch arm64 \
          -isysroot "$SDK" \
          -miphoneos-version-min=15.0 \
          -Os \
          -fvisibility=hidden \
          -fomit-frame-pointer \
          -dynamiclib \
          -install_name "@rpath/FFEX.dylib" \
          -framework Foundation \
          -framework UIKit \
          -framework Security \
          -framework CoreGraphics \
          -framework QuartzCore \
          -framework CoreFoundation \
          -lobjc -ObjC \
          -DFFEX_IOS=1 \
          -DBUILD_NUMBER=${{ github.run_number }} \
          -I Sources/ \
          Sources/FFEXMain.m \
          Sources/FFEXKeySystem.m \
          Sources/FFEXAntiCheat.m \
          Sources/FFEXCheat.m \
          Sources/FFEXModMenu.m \
          -o build/FFEX.dylib

        strip -x build/FFEX.dylib

        echo "Size: $(du -sh build/FFEX.dylib | cut -f1)"


    - name: Upload FFEX.framework
      uses: actions/upload-artifact@v4
      with:
        name: FFEX-dylib-${{ github.run_number }}
        path: build/FFEX.dylib
        retention-days: 30
